version: "3.9"
services:
  api:
    build: backend
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY
      - DATABASE_URL=postgresql://pq:pq@db/phishquest
      - REDIS_URL=redis://redis:6379
    depends_on:
      - db
      - redis
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: pq
      POSTGRES_PASSWORD: pq
      POSTGRES_DB: phishquest
    volumes:
      - pgdata:/var/lib/postgresql/data
  redis:
    image: redis:7-alpine
volumes:
  pgdata: