name: DependaSentinel
on:
  pull_request:
    branches: [main]

jobs:
  sentinel:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
    - uses: actions/checkout@v4
    - name: Run DependaSentinel
      uses: your-org/dependasentinel@v1
      with:
        fail-on-severity: moderate
        github-token: ${{ secrets.GITHUB_TOKEN }}
    - uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: dependasentinel.sarif