name: phisnap
description: Offline QR/URL phishing detector
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter: { sdk: flutter }
  cupertino_icons: ^1.0.6
  camera: ^0.10.5+7
  google_mlkit_barcode_scanning: ^0.10.0
  tflite_flutter: ^0.10.4
  url_launcher: ^6.2.2
  path_provider: ^2.1.2

dev_dependencies:
  flutter_test: { sdk: flutter }
  flutter_lints: ^3.0.1